appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EwvfTvKTxhis5gdCRwnVnw0hXY7YXsgwG+m1pFeoM/vs2TVA729g1pCvjpTkwTVgP0HRe8qNvOov5nTg3F17dudZNThIvmyW2+tKLlKLYiLxeosff9y6PqfY508aZJFlkRuUlJv5T9NJFF0tl7nXQeung1SY7qwhlAOl8l5LfzmHzmXg9BLUtiXj3hrAY6xwX60mW1sU14PZtJTaDGKpyzvCa6o/eZazsgOYHkDZB8h+O34VqzipUsv4Frzzp2M2DHWciJhh1LBEWa1he6pdHzSxuircYGgha+ND3Cd/BlmUw8vMNaUu9abFnnFGMRkLhLG11FlLWhVpHJDLFNc7+Fs0iOL05nILLZx5j8Tk3pbtsyS/iCvxcSWH92MhIqkoK939hiY2L9WAXeMWJpD3nfOiQlBgG31vIcq9SIqrHWrOZwBh2w3ZXlGof74zaj91JvIlzJin4M68kryTKgND6T5RUBnXwuymPlUyHl0xDiEBV/EqJRVRwADkp+UWNT0Ukdv9OFppsl+mESOJ8Cx8W9rj/0ksNr5odsXuehqwbdHo7xYOkXJoS4X+doDrFQ52eWvVJTK09a3wEEJ2zG7lSGyjLl8GZTMoXJbWBExUl+bpCQZ47IxyxBJyMHYDpRIZYDB7fHoUXhwfborIWtWTL3USYNAMSNZemIRzw0Uf+48=
